config/routes.rb
Rails.application.routes.draw do
  resources :listings

  devise_for :users
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :conversations do
    resources :messages
  end
  

  get '/about' => 'pages#about', as: "about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages

  validates_uniqueness_of :sender_id, scope: :recipient_id

  # This scope validation takes the sender_id and recipient_id for the conversation and checks whether a conversation exists between the two ids because we only want two users to have one conversation.

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end

  
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_rich_text :description
  has_one_attached :image
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :listing
  belongs_to :coder, foreign_key: "coder_id", class_name: "User"
  belongs_to :client, foreign_key: "client_id", class_name: "User"
end

# Please read !
# please ignore this model as for now, because I'm making this for future agile development, not for the assessment. thanks!

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings
  
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar, :conversations, :messages])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_conversation, only: %i[ show edit update destroy ]
  
    def index
      @users = User.all # To call all users from the database
      @conversations = Conversation.all # To call all conversations from the database
    end
  
    def create
      if Conversation.between(params[:sender_id], params[:recipient_id]).present?
        @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
      else
        @conversation = Conversation.create!(conversation_params)
      end
      redirect_to conversation_messages_path(@conversation)
    end

    def destroy
      @conversation.destroy
    end
  
    private
      def conversation_params
        params.permit(:sender_id, :recipient_id, :avatar)
      end

      def set_conversation
        @conversation = Conversation.find(params[:id])
      end
  
  end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]
  before_action :set_form_vars, only: %i[ new edit ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all # To call all listing in the database
    @listings = @listings.order(:created_at).reverse_order
  end

  # GET /listings/1 or /listings/1.json
  def show
   
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end
 
  # POST /listings or /listings.json d
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json 
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json 
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id]) # To call listing based on the parameter's id
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :description, :price, :closed, :user_id, :category_id, :image)
    end

    def authorize_user
      if @listing.user_id != current_user.id
        flash[:alert] = "Sorry, that's not possible"
        redirect_to listings_path
      end
    end

    def set_form_vars
      @categories = Category.all
    end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :find_conversation
  
    def index
      @messages = @conversation.messages
  
      if @messages.length > 10
        @over_ten = true
        @messages = @messages[-10..-1]
      end
  
      if params[:m]
        @over_ten = false
        @messages = @conversation.messages
      end
  
      @message = @conversation.messages.new
    end
  
    def create
      @message = @conversation.messages.new(message_params)
      if @message.save
        redirect_to conversation_messages_path(@conversation)
      end
    end
  
    def new
      @message = @conversation.messages.new
    end

    private

    def message_params
      params.require(:message).permit(:body, :user_id)
    end

    # To find a conversation based on the parameter which is the conversation id
    def find_conversation
      @conversation = Conversation.find(params[:conversation_id]) 
    end
end 

  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  
  end
end

app/helpers/application_helper.rb
require 'kramdown'
require 'kramdown-parser-gfm' 

module ApplicationHelper

    def gravatar_for(user, options = { size: 200})
        if user.avatar.attached? 
            image_tag(user.avatar, size: 40, class: "rounded-circle")
        else
            image_tag("user.png", alt: user.username, class: "rounded-circle", size: 40)
        end
    end
 
    def markdown_to_html(text)
        Kramdown::Document.new(text, input: "GFM").to_html
    end
 
    def listing_author(listing)
        user_signed_in? && current_user.id == listing.user_id
    end
    
 
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/conversations/index.html.erb
<div class="body">
    <h5 class="padding" >
        <%= link_to 'Create New Listing', new_listing_path, class: "btn btn-outline-light me-2" %>
    </h5>

    <h5 class="padding" >
        <%= link_to "Messages", conversations_path, class: "btn btn-outline-light me-2" %>
    </h5>
</div>

<div class="columns newlisting">
  

  <div class="column is-7 padding">
    <h3 class="title is-3">Conversations</h3>
    <% @conversations.each do |conversation| %>
      <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
        <% if conversation.sender_id == current_user.id %>
          <% recipient = User.find(conversation.recipient_id) %>
        <% else %>
          <% recipient = User.find(conversation.sender_id) %>
        <% end %>
        
        <% unless current_user.id == recipient %>
          
          <div class="column padding">
            <div class="inline-block nudge-down-10"><%= gravatar_for recipient, size: 32 %></div>
            <div class="inline-block"><%= link_to recipient.username, conversation_messages_path(conversation) %></div>
          </div>
          
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  

 
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
 

  <div class="field new-listing-elements">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field new-listing-elements">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="field new-listing-elements">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  
  

  <div class="field new-listing-elements">
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]} %>
  </div>


  <div class="field new-listing-elements">
    <%= form.label :image %>
    <%= form.file_field :image, accept: "image/png,image/jpg,image/jpeg", class:"btn btn-primary my-2" %>
  </div>

  <div class="actions new-listing-elements">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div class="newlisting">

    <h1>Editing Listing</h1>


    <%= form_with(model: @listing) do |form| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
 

  <div class="field new-listing-elements">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field new-listing-elements">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="field new-listing-elements">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field new-listing-elements">
    <%= form.label :closed %>
    <%= form.check_box :closed %>
  </div>

  

  <div class="field new-listing-elements">
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]} %>
  </div>


  <div class="field new-listing-elements">
    <%= form.label :image %>
    <%= form.file_field :image, accept: "image/png,image/jpg,image/jpeg", class:"btn btn-primary my-2" %>
  </div>

  <div class="actions new-listing-elements">
    <%= form.submit %>
  </div>
<% end %>




    <%= link_to 'Show', @listing %> |
    <%= link_to 'Back', listings_path %>
</div>

app/views/listings/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    
    <title>Listings</title>
    
  </head>

  <body>

    <p id="notice"><%= notice %></p>

    <h1 class="text-center">Listings</h1><br>

    <%= render 'shared/secondnav' %>

    <div class="list-group listing-padding">
      
      <% @listings.each do |listing| %>          
            
        <div class="list-group-item list-group-item-action flex-column align-items-start"><br>
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= link_to listing.title, listing %></h5>               
            <small class="text-muted"><%= time_ago_in_words(listing.created_at) %></small>
          </div>
          <p class="mb-1"><%= listing.description %></p>
          <small class="small-padding text-muted">$<%= listing.price %></small>
          <small class="small-padding text-muted"><% listing.closed %>
              <% if listing.closed == true %>
                <%= "closed" %>
              <% else %>
                <%= "open" %>
              <% end %>            
          </small>
          <small class="small-padding text-muted" >author: <%= listing.user.username %></small>
          <small class="small-padding text-muted">type: <%= listing.category.name %></small>
             
          <small class="small-padding text-muted">
            <% if current_user && current_user.id == listing.user_id %>
              <%= link_to 'Edit', edit_listing_path(listing) %>
              <%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' } %>
                 
            <% end %>
          </small>
          <br><br>
        </div>        
        
      <% end %>
    </div>
  </body>
</html>

app/views/listings/new.html.erb
<div class="body ">
    <h5 class="padding" >
        <%= link_to "Messages", conversations_path, class: "btn btn-outline-light me-2" %>
    </h5>
</div>

<div class="newlisting">
    <h1>New Listing</h1>

    <%= render 'form', listing: @listing %>
    
    <%= link_to 'Back', listings_path %>
</div>

app/views/listings/show.html.erb
<div class="newlisting padding">

  <%# need to check again what is the replacement of @listing.user.username ? %>
  <div class="columns">
    <div class="column is-8 padding2">
      <h1 class="title is-1"><%= @listing.title %></h1>
      <div class="content">
        <p class="pb3 border-bottom">Posted <%= time_ago_in_words(@listing.created_at) %> ago</p>
      </div>    
    </div>

    <div class="column is-3 is-offset-1">
     
      <div class="pr5 mb4">
        <p class="text-align-left f6">listing author:</p>
        <div class="inline-block nudge-down-10"><%= gravatar_for @listing.user, size: 32 %></div>
        <div class="inline-block"><%= @listing.user.username %></div>
      </div>
      
      <div class="padding2">
        <% if user_signed_in? && current_user.id != @listing.user_id %>
          <%= button_to "Message #{@listing.user.username}", conversations_path(sender_id: current_user.id, recipient_id: @listing.user.id), method: 'post', class:"button is-link" %>
        <% elsif user_signed_in? && current_user.id == @listing.user_id  %>
          <%= link_to "Go to Messages", conversations_path %>
        <% else %>
        <%= link_to "Sign up to message #{@listing.user.username}", new_user_registration_path %>
        <% end %>
      </div>
    </div>
  </div>



  <p>
    <strong>Price:</strong>
    $<%= @listing.price %>
  </p>

  <p>
    <strong>Status:</strong>
    <td><% @listing.closed %>
      <% if @listing.closed == true %>
        <%= "closed" %>
      <% else %>
        <%= "open" %>
      <% end %>
    </td>
  </p>

  <%# <p>
    <strong>User:</strong>
    <%= @listing.user.username %>
  

  <p>
    <strong>Category:</strong>
    <%= @listing.category.name %>
  </p>

  <div class="padding2">
    <strong>Description:</strong>
    <%= @listing.description %>
  </div>

  
  <div class="padding2">
    <% if @listing.image.attached? %>
      <p>Attached files:</p>
      <%= image_tag @listing.image, alt: @listing.title, width: 400 %>
    <% else %>
      <%= image_tag "gallery.png", alt: @listing.title, size: 125 %>
    <% end %>
  </div>

  <% if @listing.closed %>
    <h1>Sorry, this project has been Closed</h1>
  <% elsif current_user && current_user.id == @listing.user_id %>
    <h3>Note: This is your own listing</h3>
  <% end %>


  <div class="padding2">
    <% if listing_author(@listing) %>
      <div class="bg-light pa3 mb4 border-radius-3">
        
        <div class="button-group">
          <% if current_user && current_user.id == @listing.user_id %>
          <%= link_to 'Edit', edit_listing_path(@listing) %> |
          <% end %>
          <%= link_to 'Back', listings_path %>
        </div>
      </div>  
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="newmessage">
  <h1 class="title is-4">Message <%= @conversation.recipient.username %></h1>

  <% if @over_ten %>
    <%= link_to "Show previous", '?m=all', class:'button is-link' %>
  <% end %>

  <section id="messages" class="mb4">
    <% @messages.each do |message| %>
      <% if message.body %>
        <% user = User.find(message.user_id) %>
        <article class="message is-dark">
          <div class="message-body">
          <br>
          <br>
            <div class="inline-block nudge-down-10 pr2"><%= gravatar_for user, size: 32 %></div>
            <div class="inline-block"><strong><%= user.username %></strong> <%= message.message_time %></div>
            <div class="block pt4">
              <div class="f4"><%= sanitize markdown_to_html(message.body) %></div>
            </div>
          </div>
        </article>
      <% end %>
    <% end %>
  </section>
  <br>
  <br>
  <%= form_for [@conversation, @message] do |f| %>
    <%= f.rich_text_area :body, class: "textarea", placeholder: "Inquire about a listing..." %>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
    <div class="text-align-right">
      <%= f.submit "Send message", class: "button is-link is-large mt3" %>
    </div>
  <% end %>
</div>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
<title>About</title>
<meta charset="UTF-8">
<meta name="viewport" content="initial-scale=1">


</head>

<body>

    <div class="about thumbnail-text" >
        <div class="about-padding" >
            <h1 class="about-padding">About Axion&#153;</h1>
        </div>
            
        <div class="description">
            <p>Axion connects coders and clients globally to fill the gap between them in the entrepreneurial industry.</p>

            <p>The purpose of this Axion is to provide P2P supply and demand environment where now clients (buyer side) and developers, coders and programmers (seller side) can interact with each other through a transparent direct communication.</p>

            <p>In 21st century we believe that we should have more flexibility and options in the workforce. Through this marketplace now there could be a casual, part time or full-time freelancers as an option besides working or not for a company or an organisation.</p>

            <p>On the other hand, clients who have limited financial or project capacity will now be possible to develop their entrepreneurial ambitions. Therefore, this app is benevolent and provide flexibility for both parties.</p>

            <p>We hope you to maximise and take advantage of this opportunity!</p>
        </div>
        
    </div>
</body>

app/views/pages/home.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Home</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/heroes/">

    
  </head>
  <body>
    
    <main>
      <div class="px-4 py-5 my-5 text-center">
        
        <h1 class="display-5 fw-bold axion">Welcome to Axion&#153;</h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead mb-4">Find your coders or clients here and make your dreams happen.</p>
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="<%= listings_path %>" type="button" class="btn btn-primary btn-lg px-4 gap-3">Find Listings</a>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/shared/_nav.html.erb
<!doctype html>
<html lang="en">
<head>   
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
   
        
</head>

    <body>
    
        

        <main>  

            <header class="p-3 bg-dark text-white">                
                <div class="container">     
                        
                    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
                        </a>
                        <div class="axion">
                            <h3>Axion<span class="custom-trademark">&#153;</span></h3>
                        </div>
                        
                        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">         
                                                    
                        <li><a href="<%= root_path %>" class="nav-link px-2 text-white">Home</a></li>
                        <li><a href="<%= listings_path %>" class="nav-link px-2 text-white">Listings</a></li>
                        <li><a href="<%= about_path %>" class="nav-link px-2 text-white">About</a></li>
                        </ul> 

                        

                        
                        

                        

                        <div class="button" >
                            <% if user_signed_in? %>                                
                                
                                <div class="padding" >
                                    <% if current_user.avatar.attached? %>
                                        <%= image_tag current_user.avatar, height: 40 , width: 40, class: "rounded-circle" %> 
                                    <% else %>
                                        <%= image_tag "user.png", alt: "default avatar", size: 40 %>
                                    <% end %>
                                        <%= link_to current_user.username, edit_user_registration_path, class:"navbar-item" %>                                    
                                </div>
                                <div class="padding">
                                    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-light me-2" %>
                                </div>
                        
                        
                            <% else %>
                                <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-light me-2" %>
                                <%= link_to "Sign in", new_user_session_path, class: "btn btn-warning" %>
                            <% end %>
                        </div>

                        
                    </div>
                </div>
            </header>
        
        </main>


        

  

      
    </body>
</html>

app/views/shared/_secondnav.html.erb
<div class="body ">
    <h5 class="padding" >
        <%= link_to 'Create New Listing', new_listing_path, class: "btn btn-outline-light me-2" %>
    </h5>

    <h5 class="padding" >
        <%= link_to "Messages", conversations_path, class: "btn btn-outline-light me-2" %>
    </h5>

    

    
</div>
    